### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by cheind** [Henningson/Fireflies#18]
Hey @Henningson,

just saw your paper pop up in my inbox - excellent work and really useful library!

> I originally created it to research if the task of finding an optimal point-based laser pattern for structured light laryngoscopy can be reformulated as a gradient-based optimization problem. 

Interestingly, a co-worker of mine had a similar idea but never pursued it further.

All the best, and thanks for citing blendtorch :)

**Comment by Henningson** [comment]
Hey @cheind,

thanks a lot! I really appreciate it.
